# Generated by Django 2.2 on 2019-06-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='backend_django_recipes.Recipes'),
        ),
    ]
